### ISSUE TITLE
When I remote play spacewar games there's no controller icon in the remote play so I can't use the controller does anyone know why?

### ISSUE THREAD

**Issue by laissaassi** [m4dEngi/RemotePlayWhatever#41] opened 2022-01-30 23:14 UTC
When I remote play spacewar games there's no controller icon in the remote play so I can't use the controller does anyone know why?

**Comment by m4dEngi** [comment] 2022-01-31 07:21
Duplicate of #7

**Closed by m4dEngi** 2022-01-31 07:21 UTC
